import{a as L,S as I,i as m}from"./assets/vendor-f736e62a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function v(r){try{return(await L.get(`https://pixabay.com/api/?${r}`)).data}catch(o){throw console.error("Error while fetching images:",o),o}}const w=document.querySelector(".add_img_btn"),l=document.querySelector("ul"),c=document.querySelector(".loader");let p;function E(r){return Promise.all(r.map(o=>new Promise((n,a)=>{const e=new Image;e.onload=n,e.onerror=a,e.src=o.largeImageURL})))}async function P(r,o){B();try{if(await E(r),!l)throw new Error("List element not found");if(l.insertAdjacentHTML("beforeend",q(r)),p?p.refresh():p=new I("ul a",{captionsData:"alt",captionDelay:250}),b(),o!==1){const n=l.firstElementChild.getBoundingClientRect().height*2+48;setTimeout(()=>{window.scrollBy({top:n,behavior:"smooth"})},300)}r.length<15&&(h(),m.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(n){console.error("Error while preloading images:",n)}}async function y(){return b(),h(),new Promise(r=>{l&&(l.innerHTML=""),r()})}function q(r){return r.map(({webformatURL:o,largeImageURL:n,tags:a,likes:e,views:t,comments:i,downloads:d})=>`
            <li>
                <a href="${n}" alt="${a}">
                    <img src="${o}" alt="${a}" width="360" />
                    <div class="image-info">
                        <p><span class="info-label">Likes</span><br>${e}</p>
                        <p><span class="info-label">Views</span><br>${t}</p>
                        <p><span class="info-label">Comments</span><br>${i}</p>
                        <p><span class="info-label">Downloads</span><br>${d}</p>
                    </div>
                </a>
            </li>
        `).join("")}function B(){c&&(c.style.display="block",h())}function b(){c&&(c.style.display="none",w.style.display="block")}function h(){w.style.display="none"}function S(){c.style.position="absolute",c.style.top=l.offsetTop+l.offsetHeight+"px"}function $(r){c.style.position="absolute",c.style.top=r.offsetTop+r.offsetHeight+"px"}document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("search-form"),o=document.getElementById("search-img"),n=document.querySelector(".add_img_btn"),a="43273771-9fb27172998fac0872066584a";let e=1,t;r.addEventListener("submit",async s=>{if(s.preventDefault(),t=o.value.trim(),t){e=1;try{await y(),$(o),await i(t)}catch(f){g(f)}}else m.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"})});async function i(s){o.value="";const f=new URLSearchParams({key:a,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15});try{const u=await v(f);if(u.hits.length===0)throw y(),new Error("Sorry, there are no images matching your search query. Please try again!");P(u.hits,e)}catch(u){throw u}}n.addEventListener("click",async()=>{S();try{await d()}catch(s){g(s)}});async function d(){e++;try{await i(t)}catch(s){throw s}}function g(s){console.error(s),m.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
