import{a as w,S as b,i as d}from"./assets/vendor-f736e62a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function L(r){return w.get(`https://pixabay.com/api/?${r}`).then(o=>o.data).catch(o=>{throw console.error("Error while fetching images:",o),o})}const g=document.querySelector(".add_img_btn"),u=document.querySelector("ul"),a=document.querySelector(".loader");let m;function I(r){return new Promise((o,n)=>{const s=r.map(e=>new Promise((t,i)=>{const c=new Image;c.onload=()=>t(),c.onerror=l=>i(l),c.src=e.largeImageURL}));Promise.all(s).then(()=>o()).catch(e=>n(e))})}function P(r,o){E(),I(r).then(()=>{if(!u)throw new Error("List element not found");if(u.insertAdjacentHTML("beforeend",v(r)),m?m.refresh():m=new b("ul a",{captionsData:"alt",captionDelay:250}),y(),o!==1){const n=u.firstElementChild.getBoundingClientRect().height*2+48;setTimeout(()=>{window.scrollBy({top:n,behavior:"smooth"})},300)}r.length<15&&(p(),d.warning({title:"Warning",message:"There are fewer than 15 images available.",position:"topRight"}))}).catch(n=>{console.error("Error while preloading images:",n)})}function h(){return y(),p(),new Promise(r=>{u&&(u.innerHTML=""),r()})}function v(r){return r.map(({webformatURL:o,largeImageURL:n,tags:s,likes:e,views:t,comments:i,downloads:c})=>`
                <li>
                    <a href="${n}" alt="${s}">
                        <img src="${o}" alt="${s}" width="360" />
                        <div class="image-info">
    <p><span class="info-label">Likes</span><br>${e}</p>
    <p><span class="info-label">Views</span><br>${t}</p>
    <p><span class="info-label">Comments</span><br>${i}</p>
    <p><span class="info-label">Downloads</span><br>${c}</p>
</div>

                    </a>
                </li>
            `).join("")}function E(){a&&(a.style.display="block",p())}function y(){a&&(a.style.display="none",g.style.display="block")}function p(){g.style.display="none"}function q(){a.style.position="absolute",a.style.top=u.offsetTop+u.offsetHeight+"px"}function B(r){a.style.position="absolute",a.style.top=r.offsetTop+r.offsetHeight+"px"}document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("search-form"),o=document.getElementById("search-img"),n=document.querySelector(".add_img_btn"),s="43273771-9fb27172998fac0872066584a";let e=1,t;r.addEventListener("submit",async l=>{l.preventDefault(),t=o.value.trim(),t?(e=1,h().then(()=>{B(o),i()})):d.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"})});async function i(){o.value="";const l=new URLSearchParams({key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15});L(l).then(f=>{if(f.hits.length===0)throw h(),new Error("Sorry, there are no images matching your search query. Please try again!");P(f.hits,e)}).catch(f=>{d.error({title:"Error",message:f.message,position:"topRight"})})}n.addEventListener("click",()=>{q(),c()});async function c(){e++;try{await i()}catch(l){console.error(l),d.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}}});
//# sourceMappingURL=commonHelpers.js.map
